name: CI Pipeline - AgendaYA

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name:  Clonar el código del repositorio
        uses: actions/checkout@v3

      - name:  Preparar entorno Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name:  Instalar dependencias
        run: npm install

      - name:  Ejecutar Pruebas Unitarias (Jest)
        run: npx jest